# Generated by Django 5.1.1 on 2024-12-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_user_resume_user_resume_last_updated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='resume_last_updated',
            new_name='last_updated',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
