# Generated by Django 5.1.1 on 2024-12-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_resume_last_updated_user_last_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='user',
            name='resume_last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
