# Generated by Django 5.1.1 on 2024-12-06 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_user_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='resume_updated',
        ),
    ]
