# Generated by Django 5.1.1 on 2024-12-06 09:52

import base.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_remove_skills_education_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='resume_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=base.models.resume_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), base.models.validate_file_size]),
        ),
    ]
