# Generated by Django 5.1.1 on 2024-12-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_competition_image_alter_competition_prize_pool'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='caption',
            new_name='description',
        ),
        migrations.AddField(
            model_name='competition',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='image',
            field=models.ImageField(default='default_competition.jpg', upload_to='competitions/'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='prize_pool',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
